### PR TITLE
halt script execution when exception occurs in view rendering

### PR DESCRIPTION
**Pull request by errotan**
… status code. Please review this, I'm open to suggestions.

### CODE REVIEW

**Comment by errotan** [comment]
Updated.

**Comment by errotan** [comment]
Currently if a view is rendered inside a view using echo or casting with (string) and there is an exception thrown inside the subview an error text is returned to the outer view but the execution continues. According to "clean code" guidelines this is "swallowing exceptions" which is bad. This patch halts the script upon exception. What do you guys think about this?

**Comment by piotrgolasz** [comment]
Sounds interesting. Can you provide any example of this, for example a gist with some code in the Welcome_Controller?

**Comment by errotan** [comment]
https://gist.github.com/errotan/a95c28be9b3edf636ecf05f64085b8fe

**Comment by WinterSilence** [comment]
@piotrgolasz  @errotan https://github.com/koseven/koseven/blob/devel/system/guide/kohana/tutorials/basic-controller.md i add new examples in guide, but need update docs.koseven.ga.

**Comment by toitzi** [comment]
Looks good.

@errotan Any updates to this? Shall this be merged?

Sorry for asking this so oftne, but i try to regulary go over all issues and PRs to see if i can help and to keep them alive

**Comment by errotan** [comment]
The status is that I'm waiting for review on this. If you think it's good it can be merged.

**Pull request merged**
