### PR TITLE
PHPUnit Update to Version 8

### PR DESCRIPTION
**Pull request by toitzi**
### Description

PHPUnit 6 (which Koseven currently uses) is deprecated and no longer maintained.
Updated Version to 8 and did required changes. Although i had to remove some old, outdated and invalid Unit Tests. Coverage will decrase a bit cause of that.

### How Has This Been Tested

Unittests. They still pass (had to fix some).

### Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by toitzi** [comment]
I can't figure out why the unittest keeps failing, it passes on my windows system but seems to fail on linux...don't know why...anybody got a idea?

**Comment by piotrbaczek** [comment]
https://travis-ci.org/koseven/koseven/jobs/495163340

**Comment by toitzi** [comment]
@piotrbaczek yes thats wht i got, but still no clue why :/

**Comment by errotan** [comment]
The provider_csrf_token() is executed twice for PHPUnit to be able to compute the total number of tests.

**Comment by toitzi** [comment]
@errotan Are you sure? I am pretty sure unittests are not running twice ...maybe i am wrong, have you any source? Or am i understanding this wrong? Also tests are passing on my machine...thy seem to fail on linux only. Also: i don't changed anything in this function, why is it failing after update?

**Comment by toitzi** [comment]
@errotan Thanks a lot for the hint issue is fixed!

**Pull request merged**
