### PR TITLE
Unittests for koseven system classes

### PR DESCRIPTION
**Pull request by toitzi**
I think it is time to add more unittests for koseven. I will push my unittests here from time to time, so please don't merge this pull request until explicit request to merge.

### CODE REVIEW

**Comment by neo22s** [comment]
awesome!!

**Comment by piotrbaczek** [comment]
+1

**Comment by piotrbaczek** [comment]
I'll try to help

**Comment by toitzi** [comment]
Closing this, i am updating phpunit to v8 and then do pr after phpunit v8 i will try to focus on tests

**Pull request closed without merging**
