### PR TITLE
Update ORM_Behavior_Guid

### PR DESCRIPTION
**Pull request by WinterSilence**
Fix issue [class UUID not exists](https://github.com/koseven/koseven/issues/288).

### CODE REVIEW

**Comment by toitzi** [comment]
@WinterSilence Thanks for your work on Koseven and your Contributions.
As written down in our [Contributing ](https://github.com/koseven/koseven/blob/devel/CONTRIBUTING.md) Guide, i would ask you to fork Koseven Repo and only create branches in your fork. Then do a PR. Please do the same with I18n (#292). Then close this PR and PR #292 and delete both branches.

**Comment by toitzi** [comment]
Closed because of inactivity. Issue still there. If somone wants to take over feel free to do so.

**Comment by WinterSilence** [comment]
> Issue still there

It's not u personal project, need voting before close. This PR fix problem, if u disagree - explain reason.

**Comment by toitzi** [comment]
@WinterSilence sorry for closing, you are right need to vote. i will reopen.
Reason i closed:

1. Latest commit over 1 Month ago. Inactive since then.
2. Assigned to you nothing happend, also no request for review
3. You created a branch on koseven framework (see my comments from 10 days ago) - no response
4. UnitTests missing

Since it was inactive for long i thought we could close this and i would write a fix on my branch. And do a PR again on a forked branch. Wasn't able to delete branches since PR was open. But restored them and reopened pr. Sorry for closing.

**Comment by toitzi** [comment]
Fixed with #319

**Pull request closed without merging**
