### PR TITLE
use language order from the client's Accept-Language: HTTP header #121

### PR DESCRIPTION
**Pull request by errotan**

### CODE REVIEW

**Comment by knbv** [comment]
@errotan Tell me, please, why do not you use a strict comparison in lines 875,876?

**Comment by errotan** [comment]
@knbv because the calling function [ preferred_language() ] also has the $explicit argument.

**Comment by knbv** [comment]
@errotan Excuse me, do not quite understand how this is connected?

**Comment by errotan** [comment]
I don't understand your problem. Strict comparison is only used when $explicit is TRUE, otherwise the first 2 characters should be equal.

**Comment by knbv** [comment]
The substr function returns the extracted part of the string parameter; or FALSE if an error occurs or an empty string.

If you know that both values are guaranteed to be strings, then == and === are identical, because the only difference between them is that === checks whether the types are the same, not just the effective values.

Are you sure that using a non-strict comparison in this case is safe? I did not study all the code in detail, it's just a refinement, but in any case I recommend using a strict comparison.

**Comment by errotan** [comment]
Ohhh, now I get it. :) I thought you are referring about the strict comparison with $explicit, didn't come to my mind that equals (==, ===) stuff. It is safe to only use non-strict (==), beacuse all input gets through atleast one strtolower() which makes it a string a regexes (like [\w-]+) makes atleast one word character.

**Comment by knbv** [comment]
@errotan Thank you! ;)

**Comment by errotan** [comment]
So can this be merged? Thx.

**Pull request merged**
