### PR TITLE
Remove unsupported cache classes

### PR DESCRIPTION
**Pull request by toitzi**
See: #297

### CODE REVIEW

**Comment by toitzi** [comment]
Can be merged?

**Comment by piotrbaczek** [comment]
Yyyyy
I think someone might use them. The correct protocol is to deprecate them in current version, for users to be aware that they are deprecated, and then remove them in next version.

**Comment by toitzi** [comment]
@piotrbaczek 
Why? Same happend with "MySQL" driver (moved to MySQLi)

**Comment by piotrbaczek** [comment]
Oh, all right. It's some old PHP 5.x s.h.i.t.
Yeah, let's remove this. Remember to add this to version description

**Comment by toitzi** [comment]
@piotrbaczek allright, so can this be merged?

**Comment by neo22s** [comment]
looks good to me! merge ;)

**Pull request merged**
