### PR TITLE
 temporary fix for #275

### PR DESCRIPTION
**Pull request by neo22s**
temporary fix for #275

### CODE REVIEW

**Comment by neo22s** [comment]
@errotan shit closed it unintentionally wanted to add another pull request.

**Comment by neo22s** [comment]
@errotan says its due to environment variable?

**Comment by piotrbaczek** [comment]
It's time for 3.3.9 then?

**Comment by neo22s** [comment]
for me it's fine, we need to see if tests pass, also @jstrobel what's your town of residence for the naming ;)

**Comment by jstrobel** [comment]
Karlsruhe :)

**Pull request merged**
