### PR TITLE
Enable unit testing for all modules by default, upgrade tests to be compatible with current phpunit, remove old module unit test files

### PR DESCRIPTION
**Pull request by errotan**

### CODE REVIEW

**Comment by errotan** [comment]
Can anybody review this?

**Comment by errotan** [comment]
Any comment from the Koseven Team? Can this be merged?

**Comment by hightechhostel** [comment]
Hi Everyone,

Not sure if this is an appropriate post for this group but I'm looking for
a PHP/SQL programmer with Kohana experience.  Please respond directly to me
if you are interested or would like more information.

Thanks.
Darren

**Comment by jstrobel** [comment]
@hightechhostel I think a good way would be posting it to the telegram group (link on https://koseven.ga/) there are right now 100 persons there ;)

**Pull request merged**
