### PR TITLE
Add support for multiple config files

### PR DESCRIPTION
**Pull request by toitzi**
#245  Add suport for JSON and YAML configurations.

Suports PHP Variables inside yaml and json.

Unittests need to be done, please review anyway.

### CODE REVIEW

**Comment by toitzi** [comment]
@neo22s 

PHP:

````
<?php
return [
   'default' => [
	'type'   => 'openssl',
	'key'	 => 'someencryptionkey',
	'cipher' => Encrypt_Engine_Openssl::AES_256_CBC
   ]
]
````

JSON:

````
{
  "default" : {
    "type"   : "openssl",
    "key"    : "someencryptionkey",
    "cipher" : "<?php echo Encrypt_Engine_Openssl::AES_256_CBC; ?>"
  }
}
````

YAML:

````
default:
  type   : openssl
  key    : someencryptionkey
  cipher : <?php echo Encrypt_Engine_Openssl::AES_256_CBC; ?>
````

**Comment by jstrobel** [comment]
> @jstrobel Line 63: `$config = [];`
> That's the default empty array which gets returned in case no configuration is found.
> Was that what you meant?
> 
> Reason i changed it is:
> If no configuration is specified inside APPPATH but SYSPATH, it first checks SYSPATH and get's config value and then it resetted the config to empty array cause nothing found in APPATH.

Sorry haven't just seen the "part" for the changes :) Perfect thanks.

**Comment by errotan** [comment]
<?php tag in json, yaml is kinda weird and allow arbitary code to be executed (security issue?). Symfony uses this syntax: !php/const:AppBundle\Entity\BlogPost::MUM_ITEMS

**Comment by neo22s** [comment]
looks good for me ;)

@errotan thanks for pointing. Weird case that can happen but better prevent it.

**Comment by toitzi** [comment]
@errotan Allowed it cause we use Constants in some configs.
Why do you think this is a security issue? You can also write php code inside our .php config right now seems to be the same to me

**Comment by errotan** [comment]
I'm busy studying until january 29. so can't review or test until then. Can you include unit tests?

**Comment by toitzi** [comment]
@errotan added unittests

**Comment by toitzi** [comment]
Think this can be merged. Feel free to revert if you disagree.

**Pull request merged**
