### PR TITLE
Master fix test

### PR DESCRIPTION
**Pull request by phpclub**
# PR Details

Fixed passing tests, fix composer.jsion

### Description

Fixed passing tests, fix composer.jsion
All unittest worked 

### How Has This Been Tested
All test green
https://github.com/phpclub/koseven/actions/runs/9206443306

### Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by phpclub** [comment]
[Koseven](https://github.com/phpclub/koseven/actions/workflows/main.yml)

Look MR for Docker plz
https://github.com/koseven/docker/pull/1

**Comment by toitzi** [comment]
Thanks a lot! Test runs for php7+ can be removed, i think composer.json / composer.lock needs to be dumped again and updaetd, then the tests should run, i will try to look into this within this week!

**Comment by toitzi** [comment]
Mentioning #471 since i will address the failing tests for that php version too and merge them with this pr

**Comment by phpclub** [comment]
Wait!
koseven/docker: travis-devel => there is only PHP 7.3
php -v
PHP 7.3.7-2+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Jul 25, 2019 11:44:59 AM) (NTS)

Composer in master's
 "require": {
 "php": ">=7.0"
 },
Need to test from PHP7.x - PHP8.x

**Comment by phpclub** [comment]
@toitzi  look

Code: Fix bug in Memcache.php, Apcu.php

Unittest: Fix (APC,Wincache = skipped)

Workflows: Add matrix 7.1...8.3, remove memcached extension

**Comment by toitzi** [comment]
Oh wow thanks a lot! Thank you very much for your contributions. I will update the koseven docker image

**Pull request merged**
