### PR TITLE
Merge of Encrypt module branch

### PR DESCRIPTION
**Pull request by svenbw**
Support both mcrypt and openssl encryption methods trough a encrypt module.
Solves #14

### CODE REVIEW

**Comment by neo22s** [comment]
Theres an error on Travis ;)

**Comment by piotrgolasz** [comment]
Error says "Class Encrypt not found". This module has to be enabled in bootstrap ;)

**Comment by svenbw** [comment]
I've loaded the module by modifying the test bootstrap file (loading the module there, just like the unittest module). The second option is to enable it by default in the Kohana bootstrap.php file.

Unit tests pass, but not for PHP7 since the default test use mcrypt in the tests.

**Comment by neo22s** [comment]
this looks good to me! someone else could test it?

I will just merge it and test better , thanks a lot @svenbw

**Pull request merged**
