### PR TITLE
Replaced download link

### PR DESCRIPTION
**Pull request by knbv**
Users should see a list of changes ;)

### CODE REVIEW

**Comment by neo22s** [comment]
but also the download link I think...

**Comment by knbv** [comment]
There are also links for downloading
https://github.com/koseven/koseven/releases/tag/3.3.7

**Comment by neo22s** [comment]
direct link I mean hehehe but doesnt matter

**Comment by neo22s** [comment]
here should be done also https://github.com/koseven/koseven/blob/gh-pages/index.md

And please before submitting PR we need a issue so we can discuss before we do the work. To avoid this. I like everything to be voted, I feel bad about closing a PR without merging it.

**Comment by knbv** [comment]
Sorry, I thought that this is too small a change to create a discussion :)

Thank you!

**Comment by knbv** [comment]
Sorry, I thought that this is too small a change to create a discussion. However, you can discuss it right here :)

Thank you!

**Comment by neo22s** [comment]
no problem heheh its to keep track of changes too. thanks a lot.

**Pull request merged**
