### PR TITLE
Renamed Kohana Classes to Koseven and created a compatibility module

### PR DESCRIPTION
**Pull request by toitzi**
See Issue #282

### CODE REVIEW

**Comment by neo22s** [comment]
Should we merge this to Devel and test?

**Comment by toitzi** [comment]
Don't merge...issues occur when you try to include Kohana classes directly.

eg.: `require SYSPATH.'classes/kohana.php';`

We should  not use it as model for full compatiblity we should keep it in "/system"

Further testing over the weekend.

**Comment by toitzi** [comment]
@neo22s 
Think i found a solution:

add the following to `Koseven_Core`:

````
/**
 * @var boolean  Kohana Compatibility mode
 */
public static $compatibility = TRUE;
````

after `spl_autoload_register` inside `bootstrap.php`

````
if (Koseven::$compatibility AND is_file(APPPATH.'classes/Kohana'.EXT))
{
    require APPPATH.'classes/Kohana'.EXT;
}
````
We can now also autoload the module if `Koseven::$compatibility` is true.

And last but not least add the following section inside `Koseven::find_file` function:
````
...
/**
 *     NOTE: This check is only needed if we are PRE-Initialization and in Compatibility mode
 *     Only performing before Initialization makes sure that no `stpos` operations, etc get called
 *     on custom classes and without beeing necessary
 **/ 
if (!Koseven::$_init AND Koseven::$compatibility AND strpos($path, 'kohana') !== FALSE) 
{                 
     $found = MODPATH.'kohana'.DIRECTORY_SEPARATOR.$path;
     if (!is_file($found))
     {
          $found = FALSE;
     }
}

....
````
This makes sure we can keep it as a module, cause if kohana classes are loaded
PRE-Initializaton (like the one from @neo22s  in his project yclass) - which means even before modules are loaded - this function makes sure to check them inside the kohana module folder

**Comment by neo22s** [comment]
What do you all think guys? 

I mean for me when I do the migration I have no issue into renaming all the project. Will take maybe few minutes but that's all.

**Pull request closed without merging**
