### PR TITLE
Updated image module tests

### PR DESCRIPTION
**Pull request by svenbw**
# PR Details

Updated the tests for the image module

### Description

Most functions are covered in tests now.

### Related Issue

No related issues.

### How Has This Been Tested

Only tests where added.

### Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [X] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by toitzi** [comment]
Awesome!

**Comment by svenbw** [comment]
Imagick is available in the CI but test coverage is still 0%.

**Comment by svenbw** [comment]
Installed version of Ubuntu doesn't support webp (yet).

**Comment by toitzi** [comment]
See #369 . Thanks a lot! Great work 🎉

**Pull request closed without merging**
