### PR TITLE
Add check to order_by clause

### PR DESCRIPTION
**Pull request by toitzi**
See #323 

Please review and if correct merge asap.

### CODE REVIEW

**Comment by neo22s** [comment]
ok, I agree on @errotan to send an exception if not exactly ASC or DESC. I did not think on that scenario and really easy to solve.

Thanks a lot for the job guys!

**Comment by toitzi** [comment]
@errotan yes you are right, i absolutley agree with you...i updated the pr please review!

**Comment by neo22s** [comment]
agree! all good ;)

**Comment by svenbw** [comment]
The strtoupper should be moved from below the test to above. `asc` and `desc` are also valid options.

**Comment by toitzi** [comment]
@svenbw of course you are right...where is my head right now 😸

**Comment by neo22s** [comment]
@toitzi sleep deprivation!! ;) great job and thanks again

**Pull request merged**
