### PR TITLE
Unittests on Windows Systems

### PR DESCRIPTION
**Pull request by toitzi**

### CODE REVIEW

**Comment by toitzi** [comment]
All tests are passing now on my windows system fine.

Think we can safley merge this into devel?

**Comment by WinterSilence** [comment]
~~~
['userguide/adding', 'guide'.DIRECTORY_SEPARATOR.'userguide/adding.md'],
~~~
why u not replace all separators? i think it's not clear solution

**Comment by toitzi** [comment]
@WinterSilence Yes of course...did it ;)

**Comment by WinterSilence** [comment]
@toitzi i check tomorrow and add

**Comment by toitzi** [comment]
@WinterSilence confirm?

**Pull request merged**
